export const PAGE_SIZE = 20
export const STORAGE_KEY = 'recentPatients'

export const FIELD_MAP = {
    dt: 'Дата актуальности признаков',
    target: 'Таргет',
    id: 'ID клиента',
    w: 'Вес',
    age: 'Возраст',
    gender: 'Пол',
    city_smart_name: 'Город (SMART)',
    adminarea: 'Регион',
    addrref: 'Регион отделения',
    tz_msk_timedelta: 'Часовой пояс (от МСК)',
    client_active_flag: 'Активность клиента',
    nonresident_flag: 'Нерезидент РФ',
    blacklist_flag: 'Черный список',
    lifetimeComp: 'Время жизни абонента конкурента',
    days_to_last_transaction: 'Дней до посл. транзакции',
    days_after_last_request: 'Дней после посл. запроса',
    period_last_act_ad: 'Дата посл. активности (AD)',

    incomeValue: 'Значение дохода',
    incomeValueCategory: 'Категория дохода',
    salary_6to12m_avg: 'Усреднённая ЗП (6-12 мес)',
    first_salary_income: 'Внешние: Первый зарплатный доход',
    accountsalary_out_flag: 'Наличие зарплатного счета',
    per_capita_income_rur_amt: 'Среднедушевой доход (Росстат)',
    salary_median_in_gex_r1: 'Гео: Медианная ЗП',
    profit_income_out_rur_amt_12m: 'Ср. опер. доход (12 мес)',
    profit_income_out_rur_amt_9m: 'Ср. опер. доход (9 мес)',
    profit_income_out_rur_amt_l2m: 'Опер. доход Profit3 (мес T-4)',

    turn_cur_cr_avg_act_v2: 'Ср. текущий кред. оборот (12 мес)',
    turn_cur_cr_avg_v2: 'Ср. кред. оборот (12 мес)',
    turn_cur_cr_max_v2: 'Макс. кред. оборот (12 мес)',
    turn_cur_cr_min_v2: 'Мин. кред. оборот (12 мес)',
    turn_cur_cr_sum_v2: 'Общий кред. оборот (12 мес)',
    avg_cur_cr_turn: 'Ср. кред. оборот (3 мес)',
    avg_credit_turn_rur: 'Ср. кред. оборот (все счета, 3 мес)',
    turn_cur_cr_7avg_avg_v2: 'Ср. кред. оборот (7 дней)',

    turn_cur_db_sum_v2: 'Общий дебет. оборот (12 мес)',
    turn_cur_db_avg_act_v2: 'Ср. текущий дебет. оборот (12 мес)',
    turn_cur_db_avg_v2: 'Ср. дебет. оборот (12 мес)',
    turn_cur_db_max_v2: 'Макс. дебет. оборот (12 мес)',
    turn_cur_db_min_v2: 'Мин. дебет. оборот (12 мес)',
    avg_cur_db_turn: 'Ср. дебет. оборот (3 мес)',
    avg_debet_turn_rur: 'Ср. дебет. оборот (все счета, 3 мес)',
    turn_cur_db_7avg_avg_v2: 'Ср. дебет. оборот (7 дней)',
    diff_avg_cr_db_turn: 'Разница ср. кред. и дебет. (3 мес)',

    turn_fdep_db_sum_v2: 'Депозиты: Общий дебет. оборот (12 мес)',
    turn_fdep_db_avg_v2: 'Депозиты: Ср. дебет. оборот (12 мес)',
    turn_fdep_db_avg_act_v2: 'Депозиты: Ср. тек. дебет. оборот (12 мес)',
    avg_fdep_db_turn: 'Депозиты: Ср. дебет. оборот (3 мес)',
    avg_fdep_cr_turn: 'Депозиты: Ср. кред. оборот (3 мес)',
    turn_save_db_min_v2: 'Накопительные: Мин. дебет. оборот (12 мес)',
    turn_save_cr_max_v2: 'Накопительные: Макс. кред. оборот (12 мес)',

    curr_rur_amt_cm_avg: 'Ср. остаток на счетах (12 мес)',
    curr_rur_amt_3m_avg: 'Ср. остаток на счетах (3 мес)',
    curr_rur_amt_cm_avg_inc_v2: 'Прирост ср. суммы на счетах (2 мес)',
    curr_rur_amt_cm_avg_period_days_ago_v2: 'Ср. сумма на счетах (2 мес назад)',
    curbal_usd_amt_cm_avg: 'Ср. баланс USD (3 мес)',
    dda_rur_amt_curr_v2: 'Сумма "До востребования"',
    dda_rur_amt_3m_avg: 'Ср. "До востребования" (3 мес)',
    total_rur_amt_cm_avg: 'Собств. средства: Ср. остаток (12 мес)',
    total_rur_amt_cm_avg_period_days_ago_v2: 'Собств. средства: Ср. сумма (2 мес назад)',
    avg_balance_rur_amt_1m_af: 'Ср. баланс (все фабрики, 1 мес)',
    min_balance_rur_amt_1m_af: 'Мин. баланс (все фабрики, 1 мес)',
    max_balance_rur_amt_1m_af: 'Макс. баланс (все фабрики, 1 мес)',
    min_balance_rur_amt_6m_af: 'Мин. баланс (все фабрики, 6 мес)',
    express_rur_amt_cm_avg: 'Экспресс счета: Ср. остаток (12 мес)',

    turn_other_cr_avg_act_v2: 'Другие счета: Ср. тек. кред. оборот (12 мес)',
    turn_other_cr_sum_v2: 'Другие счета: Общий кред. оборот (12 мес)',
    turn_other_db_max_v2: 'Другие счета: Макс. дебет. оборот (12 мес)',

    loanacc_rur_amt_cm_avg: 'Кред. счета: Ср. остаток (12 мес)',
    loanacc_rur_amt_curr_v2: 'Кред. счета: Текущая сумма',
    loanacc_rur_amt_cm_avg_inc_v2: 'Кред. счета: Динамика остатка',
    cred_dda_rur_amt_3m_avg: 'Тек. счета кредитов: Ср. остаток (3 мес)',
    ovrd_sum: 'Сумма просрочки',
    total_sum: 'Общая сумма просрочки (все время)',
    loan_cnt: 'Кредитов наличными (с 2018)',
    loan_cur_amt: 'Сумма запрашиваемого кредита',
    avg_loan_cnt_with_insurance: 'Кредиты со страховкой (с 2018)',
    pil: 'Количество кредитов наличными',
    acard: 'Количество Альфа-карт',

    hdb_bki_total_cnt: 'БКИ: Всего обращений',
    hdb_bki_total_products: 'БКИ: Всего кред. продуктов (осн. заемщик)',
    hdb_bki_total_active_products: 'БКИ: Активных кред. продуктов',
    hdb_bki_active_pil_cnt: 'БКИ: Активных кредитов',
    hdb_bki_total_pil_cnt: 'БКИ: Всего кредитов',
    hdb_bki_last_product_days: 'БКИ: Дней с посл. продукта',
    hdb_bki_total_max_limit: 'БКИ: Макс. кред. лимит (все время)',
    hdb_outstand_sum: 'БКИ: Сумма задолженности',
    hdb_ovrd_sum: 'БКИ: Сумма просрочки',
    hdb_bki_total_max_overdue_sum: 'БКИ: Макс. сумма просрочки (все время)',

    hdb_bki_total_cc_max_limit: 'БКИ: Макс. лимит кред. карты',
    hdb_bki_active_cc_max_limit: 'БКИ: Лимит активной кред. карты',
    hdb_bki_active_cc_max_outstand: 'БКИ: Макс. долг по активной кред. карте',
    hdb_bki_active_cc_max_overdue: 'БКИ: Макс. просрочка активной кред. карты',
    hdb_bki_total_cc_max_overdue: 'БКИ: Макс. просрочка кред. карты (все время)',

    hdb_bki_total_pil_max_limit: 'БКИ: Макс. лимит кредита',
    hdb_bki_active_pil_max_limit: 'БКИ: Макс. лимит активного кредита',
    hdb_bki_total_pil_max_overdue: 'БКИ: Макс. просрочка кредита (все время)',
    hdb_bki_total_pil_max_del90: 'БКИ: Просрочек >90 дн. по кредиту',
    hdb_bki_total_pil_last_days: 'БКИ: Дней с посл. кредита',

    hdb_bki_total_ip_max_limit: 'БКИ: Макс. лимит ипотеки',
    hdb_bki_total_ip_cnt: 'БКИ: Кол-во ипотек',
    hdb_bki_total_auto_max_limit: 'БКИ: Макс. лимит автокредита',

    hdb_bki_total_micro_cnt: 'БКИ: Кол-во микрокредитов',
    hdb_bki_total_micro_max_overdue: 'БКИ: Макс. просрочка микрокредита',

    hdb_other_outstand_sum: 'БКИ: Задолженность в др. банках',
    hdb_other_active_max_psk: 'БКИ: Макс. ПСК в др. банках',
    hdb_bki_other_active_pil_outstanding: 'БКИ: Долг по кредитам в др. банках',
    hdb_bki_other_active_ip_outstanding: 'БКИ: Долг по ипотеке в др. банках',
    hdb_relend_outstand_sum: 'БКИ: Задолженность (рефинанс)',
    hdb_relend_active_max_psk: 'БКИ: Макс. ПСК (рефинанс)',
    other_credits_count: 'Кредитов в др. банках',
    bki_total_products: 'Всего кред. продуктов (клиент)',
    bki_total_active_products: 'Активных кред. продуктов (клиент)',
    bki_active_auto_cnt: 'Активных автокредитов',
    bki_total_auto_cnt: 'Всего автокредитов',
    bki_total_il_max_limit: 'Макс. лимит кредита (IL)',
    bki_total_max_limit: 'Макс. кред. лимит (общий)',
    bki_total_oth_cnt: 'Всего продуктов "Другое"',

    dp_ils_avg_salary_1y: 'Цифр. профиль: Ср. ЗП (1 год)',
    dp_ils_avg_salary_2y: 'Цифр. профиль: Ср. ЗП (2 года)',
    dp_ils_avg_salary_3y: 'Цифр. профиль: Ср. ЗП (3 года)',
    dp_ils_salary_ratio_1y3y: 'Цифр. профиль: Коэф. ЗП (1-3 года)',
    dp_ils_paymentssum_avg_12m: 'Цифр. профиль: Платежи (12 мес)',
    dp_ils_paymentssum_avg_6m: 'Цифр. профиль: Платежи (6 мес)',
    dp_ils_paymentssum_avg_6m_current: 'Цифр. профиль: Платежи (6 мес, тек.)',
    dp_ils_paymentssum_month_avg: 'Цифр. профиль: Платежи (мес. ср.)',
    dp_ils_accpayment_avg_12m: 'Цифр. профиль: Выплаты на сч. (12 мес)',
    dp_ils_accpayment_avg_6m: 'Цифр. профиль: Выплаты на сч. (6 мес)',
    dp_ils_accpayment_avg_6m_current: 'Цифр. профиль: Выплаты на сч. (6 мес, тек.)',
    dp_ils_accpayment_avg_3m: 'Цифр. профиль: Выплаты на сч. (3 мес)',
    dp_ils_accpayment_month_avg: 'Цифр. профиль: Выплаты на сч. (мес. ср.)',

    dp_payoutincomedata_payout_avg_3_month: 'Цифр. профиль: Выплаты (ср. 3 мес)',
    dp_payoutincomedata_payout_max_3_month: 'Цифр. профиль: Выплаты (макс. 3 мес)',
    dp_payoutincomedata_payout_sum_3_month: 'Цифр. профиль: Выплаты (сумма 3 мес)',
    dp_payoutincomedata_payout_avg_6_month: 'Цифр. профиль: Выплаты (ср. 6 мес)',
    dp_payoutincomedata_payout_max_6_month: 'Цифр. профиль: Выплаты (макс. 6 мес)',
    dp_payoutincomedata_payout_avg_prev_year: 'Цифр. профиль: Выплаты (ср. прошл. год)',

    dp_ils_total_seniority: 'Цифр. профиль: Общий стаж',
    dp_ils_max_seniority: 'Цифр. профиль: Макс. стаж',
    dp_ils_days_from_last_doc: 'Цифр. профиль: Дней с посл. документа',
    dp_ils_cnt_changes_1y: 'Цифр. профиль: Смен работы (1 год)',
    dp_ils_uniq_companies_1y: 'Цифр. профиль: Уник. компаний (1 год)',
    dp_ils_employeers_cnt_last_month: 'Цифр. профиль: Работодателей (посл. мес)',
    dp_ils_avg_simultanious_jobs_5y: 'Цифр. профиль: Ср. паралл. работы (5 лет)',
    dp_ils_days_multiple_job_cnt_5y: 'Цифр. профиль: Дней множ. работ (кол-во, 5 лет)',
    dp_ils_days_multiple_job_share_2y: 'Цифр. профиль: Доля дней множ. работ (2 года)',
    dp_ils_days_ip_share_5y: 'Цифр. профиль: Доля дней ИП (5 лет)',
    dp_ils_ipkcurrentyear_currentyearpensfactor: 'Цифр. профиль: ИПК пенсионный фактор',

    dp_ewb_last_employment_position: 'Цифр. профиль: Последняя должность',
    dp_ewb_last_organization: 'Цифр. профиль: Посл. организация',
    dp_ewb_dismissal_due_contract_violation_by_lb_cnt: 'Цифр. профиль: Увольнения (нарушения)',
    dp_address_unique_regions: 'Цифр. профиль: Уник. регионов',

    summarur_1m_purch: 'Сумма покупок (тек. мес)',
    avg_amount_daily_transactions_90d: 'Ср. дневная сумма транзакций (90 дней)',
    avg_3m_all: 'Траты: Все категории (3 мес)',
    avg_6m_all: 'Траты: Все категории (6 мес)',
    avg_3m_no_cat: 'Траты: Без категории (3 мес)',

    avg_by_category__amount__sum__cashflowcategory_name__supermarkety: 'Траты: Супермаркеты',
    avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: 'Траты: Гипермаркеты',
    avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov: 'Траты: Сеть супермаркетов',
    avg_by_category__amount__sum__cashflowcategory_name__kafe: 'Траты: Кафе',
    avg_by_category__amount__sum__cashflowcategory_name__produkty: 'Траты: Продукты',
    avg_by_category__amount__sum__cashflowcategory_name__odezhda: 'Траты: Одежда',
    avg_by_category__amount__sum__cashflowcategory_name__kosmetika: 'Траты: Косметика',
    avg_by_category__amount__sum__cashflowcategory_name__oteli: 'Траты: Отели',
    avg_by_category__amount__sum__cashflowcategory_name__puteshestvija: 'Траты: Путешествия',
    avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: 'Траты: Электронные деньги',
    avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete: 'Траты: Реклама в интернете',
    avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet: 'Траты: Платежи через интернет',
    avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii: 'Траты: Зарубежные фин. операции',
    avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 'Снятие наличных (сумма/мес)',

    avg_6m_money_transactions: 'Траты: Фин. услуги (6 мес)',
    avg_3m_money_transactions: 'Траты: Фин. услуги (3 мес)',
    avg_6m_clothing: 'Траты: Одежда (6 мес)',
    avg_6m_restaurants: 'Траты: Рестораны/Фастфуд (6 мес)',
    avg_6m_hotels: 'Траты: Отели (6 мес)',
    avg_6m_travel: 'Траты: Турагентства (6 мес)',
    avg_6m_government_services: 'Траты: Платежи в бюджет (6 мес)',
    avg_3m_healthcare_services: 'Траты: Мед. услуги (3 мес)',

    amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: 'Снятие наличных (90 дней)',
    amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi: 'Эл. деньги (90 дней)',

    by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp: 'Исх. платежи СБП (сумма/мес)',
    by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp: 'Вх. платежи СБП (сумма/мес)',
    by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: 'Переводы по номеру тел. (сумма/мес)',
    by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps: 'Платёж за моб. через ПС (сумма/мес)',
    by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami: 'Перевод между своими сч. (сумма/мес)',
    by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu: 'Перевод с карты на карту (сумма/мес)',

    transaction_category_supermarket_sum_cnt_m2: 'Транзакции: Супермаркеты (кол-во, 2 мес)',
    transaction_category_supermarket_percent_cnt_2m: 'Транзакции: Супермаркеты (% кол-ва, 2 мес)',
    transaction_category_supermarket_inc_cnt_2m: 'Транзакции: Супермаркеты (рост, 2 мес)',
    transaction_category_supermarket_sum_cnt_m3_4: 'Транзакции: Супермаркеты (кол-во, 3-4 мес)',
    transaction_category_supermarket_sum_amt_d15: 'Транзакции: Супермаркеты (сумма, 15 дн)',
    transaction_category_supermarket_sum_cnt_d15: 'Транзакции: Супермаркеты (кол-во, 15 дн)',

    transaction_category_restaurants_percent_cnt_2m: 'Транзакции: Рестораны (% кол-ва, 2 мес)',
    transaction_category_restaurants_percent_amt_2m: 'Транзакции: Рестораны (% суммы, 2 мес)',
    transaction_category_restaurants_sum_amt_m2: 'Транзакции: Рестораны (сумма, 2 мес)',

    transaction_category_fastfood_percent_cnt_2m: 'Транзакции: Фастфуд (% кол-ва, 2 мес)',
    transaction_category_cash_percent_amt_2m: 'Транзакции: Cash (% суммы, 2 мес)',

    mob_cnt_days: 'Входов в Альфа-Мобайл (за 90 дн)',
    mob_cover_days: 'Доля дней активности в АМ (90 дн)',
    mob_total_sessions: 'Сессий в АМ (90 дн)',
    device_iphone_avg: 'Доля сессий iPhone (90 дн)',
    cntBlockWavg6m: 'Блокировок (ср. 6 мес)',
    cntOnnRinCallAvg6m: 'Вх. звонков в роуминге (ср. 6 мес)',
    cntRegionTripsWavg1m: 'Поездок в регионы (ср. 1 мес)',
    cntVoiceOutMob6m: 'Исх. звонков (ср. 6 мес)',
    smsInWavg6m: 'Вх. SMS (ср. 6 мес)',
    calledCtnOutGroup: 'Размер группы общения (исх.)',
    businessTelSubs: 'Абонентов Business в группе',
    winback_cnt: 'Возвращений WinBack',

    uniV5: 'Скоринг V5',
    vert_pil_last_credit_step_screen_view_3m: 'События: Last Credit Step (3 мес)',
    vert_pil_loan_application_success_3m: 'События: Loan Success (3 мес)',
    vert_pil_fee_discount_change_3m: 'События: Fee Discount Change (3 мес)',
    vert_pil_sms_success_3m: 'События: SMS Success (3 мес)',
    vert_ghost_close_dpay3_last_days: 'Дней до закр. призрака (Daily Pay)',
    vert_has_app_ru_tinkoff_investing: 'App: Тинькофф Инвестиции',
    vert_has_app_ru_vtb_invest: 'App: ВТБ Инвестиции',
    vert_has_app_ru_cian_main: 'App: ЦИАН',
    vert_has_app_ru_raiffeisennews: 'App: Райффайзен',

    label_Below_50k_share_r1: 'Внешние: Доля <50k (R1)',
    label_500k_to_1M_share_r1: 'Внешние: Доля 500k-1M (R1)',
    label_Above_1M_share_r1: 'Внешние: Доля >1M (R1)',
}